# Generated by Django 4.2.4 on 2023-11-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('User_Id', models.AutoField(auto_created=True, default=101, primary_key=True, serialize=False)),
                ('User_Name', models.CharField(max_length=100)),
                ('User_Password', models.CharField(max_length=100)),
                ('User_Fullname', models.CharField(max_length=100)),
                ('User_Age', models.IntegerField(max_length=100)),
                ('User_Img', models.ImageField(blank=True, null=True, upload_to='')),
                ('User_Gender', models.CharField(max_length=100)),
                ('User_Phone', models.IntegerField(max_length=100)),
                ('User_Email', models.EmailField(max_length=100)),
                ('User_Dob', models.DateField(max_length=100)),
            ],
        ),
    ]
