# Generated by Django 4.2.4 on 2023-11-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='User_Id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
