# Generated by Django 4.2.4 on 2023-11-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_users_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='User_Id',
            field=models.AutoField(auto_created=True, default=101, primary_key=True, serialize=False),
        ),
    ]
