# Generated by Django 4.2.4 on 2023-11-30 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_users_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Desc', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('Cover_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Article', models.CharField(max_length=100)),
                ('related_img', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
