# Generated by Django 4.2.4 on 2023-12-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_blogs_blog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='Blog_User',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
    ]
