# Generated by Django 4.2.4 on 2023-12-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_blogs_blog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='Desc',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Title',
            field=models.CharField(max_length=1000),
        ),
    ]
