# Generated by Django 4.2.4 on 2023-12-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_blogs_desc_alter_blogs_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='Blog_User',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
