# Generated by Django 4.2.4 on 2023-12-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_blogs_blog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='id',
        ),
        migrations.AddField(
            model_name='blogs',
            name='Blog_id',
            field=models.AutoField(auto_created=True, default=101, primary_key=True, serialize=False),
        ),
    ]
