# Generated by Django 4.2.4 on 2023-12-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_blogs_id_blogs_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='Blog_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
